baseURL = "https://hustshawn.github.io"
languageCode = "en-us"
title = "Shawn's Blog with Hugo"
theme = "cayman-hugo-theme"

[params]
  # Cayman theme required
  project_name = "Shawn's Blog"
  project_tagline = "Engineering | Cloud Native | Architecture"
  author = "Shawn Zhang"
  # Footer text, can be markdown
  footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [Github](https://github.com/hustshawn/hustshawn.github.io)."
  disqusShortname = "hustshawn-github-io"

  # Styles
  # Breakpoints
  large_breakpoint = "64em"
  medium_breakpoint = "42em"

  # Header colors
  header_heading_color = "#fff"
  header_background_color = "#159957"
  header_background_color_secondary = "#155799"

  # Text colors
  section_headings_color = "#159957"
  body_text_color = "#606c71"
  body_link_color = "#1e6bb8"
  blockquote_text_color = "#819198"

  # Code colors
  code_background_color = "#f3f6fa"
  code_text_color = "#567482"

  # Border colors
  border_color = "#dce6f0"
  table_border_color = "#e9ebec"
  hr_border_color = "#eff0f1"


[menu]
  [[menu.nav]]
    name = "Blog"
    url = "/"
    weight = 1
  [[menu.nav]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.nav]]
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.nav]]
    name = "RSS"
    url = "/index.xml"
    weight = 4
